sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/5.0.gemfile
before_install: gem install bundler -v 1.13.7
script:
  - bundle exec rake

