sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
gemfiles:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/5.0.gemfile
script:
  - bundle exec rake

